status: add a report on aarch64/KASAN
freebsd/freebsd-doc pull request #137
Opened 2023-03-24 00:21 UTC by kevans91

Just a general notification that it's been added, solicit wider testing.

CC @zxombie @markjdb

2023-03-24 00:45 UTC, pauamma approved these changes
Other than that, LGTM.

2023-03-24 00:45 UTC, pauamma commented on website/content/en/status/report-2023-01-2023-03/aarch64-kasan.doc
> +As of 89c52f9d59fa, the kernel address sanitizer that was previously exclusive to amd64 has now been ported to arm64.
gitref:89c52f9d59fa[repository=src]

2023-03-24 03:38 UTC, pauamma approved these changes

2023-03-24 09:31 UTC, lsalvadore requested changes
Thanks @kevans91. 

In addition to the inline comment I have written, could you also please rename your file with the `.adoc` extension instead of `.doc`? Thanks.

2023-03-24 09:31 UTC, lsalvadore commented on website/content/en/status/report-2023-01-2023-03/aarch64-kasan.doc
> +- BHyve (WIP)
This will not be rendered as intended. To get an unsorted list you need to:
- add an empty line before your list;
- replace all `-` with `*`.

2023-03-24 09:32 UTC, lsalvadore commented
@sergio-carlavilla, @dbaio: Added as reviewers to ask them for mentor approval.

2023-03-24 09:56 UTC, lsalvadore commented on website/content/en/status/report-2023-01-2023-03/aarch64-kasan.doc
> +- BHyve (WIP)
I made a mistake: adding the empty line should be enough. No need to replace `-` with `*`.

2023-03-24 15:04 UTC, kevans91 commented
Whoops, I thought I had made it .adoc like the other files already present but I must have focused a bit too much on the rest of the name...

2023-03-25 01:08 UTC, dbaio commented on website/content/en/status/report-2023-01-2023-03/aarch64-kasan.adoc
> +Sponsor: Klara, Inc.
We need to add a  `+` sign at the end of the first line to display both sponsors separately. This is a minor issue that can be fixed when pushing the commit.

```
Sponsor: Juniper Networks, Inc. +
Sponsor: Klara, Inc.
```

And thanks for your work!

2023-03-26 09:54 UTC, lsalvadore commented on website/content/en/status/report-2023-01-2023-03/aarch64-kasan.adoc
> +Sponsor: Klara, Inc.
@dbaio: Can I assume this patch mentor approved once I fix the sponsor lines? Unless @kevans91 wants to commit it himself of course.

2023-03-26 11:56 UTC, dbaio commented on website/content/en/status/report-2023-01-2023-03/aarch64-kasan.adoc
> +Sponsor: Klara, Inc.
yes, please go ahead.
and thanks again.

2023-03-27 21:01 UTC, lsalvadore commented
Thanks @kevans91, merged with commit https://github.com/freebsd/freebsd-doc/commit/be86256cba5a9796c709f3b34ba9a103cff17c6b.

2023-03-27 21:01 UTC, closed without merging