Add Puppet status report
freebsd/freebsd-doc pull request #190
Opened 2023-06-17 06:14 UTC by smortex

2023-06-17 08:21 UTC, lsalvadore requested changes
Thanks for your report, I made a few inline comments.

Could you also please put one sentence per line? Thanks.

2023-06-17 08:21 UTC, lsalvadore commented on website/content/en/status/report-2023-04-2023-06/puppet.adoc
> +Puppet is a Free Software configuration management tool, composed of a source of trust (Puppet Server) that describes the expected configuration of machines with a domain-specific language, and an ag
s/which enforce the actual configuration match the expected one/which enforces that the actual configuration matches the expected one/

2023-06-17 08:21 UTC, lsalvadore commented on website/content/en/status/report-2023-04-2023-06/puppet.adoc
> +Since our last status report, the Puppet Team maintained the Puppet 6 and Puppet 7 ports up to date.
I suggest something more direct and more focused on today: "The Puppet team is maintaining Puppet 6 and Puppet 7 ports, which are all up to date."

2023-06-17 08:21 UTC, lsalvadore commented on website/content/en/status/report-2023-04-2023-06/puppet.adoc
> +Puppet 8 has been recently released and was added to the ports tree.
s/was added/has been added/

2023-06-17 08:21 UTC, lsalvadore commented on website/content/en/status/report-2023-04-2023-06/puppet.adoc
> +For now, the Puppet 7 remains the default Puppet version for ports depending on Puppet.  The Puppet Community is hard at work making sure the various Puppet modules work with the latest code and at t
s/switch Puppet 8/switch to Puppet 8/

2023-06-17 10:41 UTC, igalic requested changes
aside from the suggested changes, i highly recommend writing one sentence per line, as that makes these reviews easier, as well as future diffs.

although status reports don't usually see much editing after release, it's a very good idea to get used to this style

2023-06-17 10:41 UTC, igalic commented on website/content/en/status/report-2023-04-2023-06/puppet.adoc
> +For now, the Puppet 7 remains the default Puppet version for ports depending on Puppet.  The Puppet Community is hard at work making sure the various Puppet modules work with the latest code and at t
s/For now, the Puppet 7 remains the default/For now, Puppet 7 remains the default/

Puppet version for ports depending on Puppet.  The Puppet Community is hard at work making sure the various Puppet modules work with the latest code and at the time of writing this report, updating to Puppet 8 may be challenging.

s/The situation is getting better every day, and we expect to switch Puppet 8 as the default/The situation is getting better every day, and we expect to switch to Puppet 8 as the default/

2023-06-17 19:49 UTC, smortex commented
@lsalvadore, @igalic I amended my commit to include your changes and separate each sentence with a new line. Thanks!

2023-06-18 00:13 UTC, pauamma commented on website/content/en/status/report-2023-04-2023-06/puppet.adoc
> +The situation is getting better every day, and we expect to switch to Puppet 8 as the default version of Puppet in a few months, when the wave of modules update is finished.
s/modules update/module updates/

2023-06-19 18:40 UTC, pauamma approved these changes

2023-06-20 13:41 UTC, lsalvadore approved these changes

2023-07-12 20:57 UTC, closed without merging