Update _index.adoc Change geli ealgo example to current default
freebsd/freebsd-doc pull request #258
Opened 2023-09-21 13:49 UTC by garrettboone

Current example of blowfish is no longer an option and geli(8) says AES-XTS is the default.

2023-09-21 13:50 UTC, sergio-carlavilla commented
Thanks for the patch, I'll merge it

2023-09-21 13:52 UTC, garrettboone commented
I just noticed I forgot to change the verbiage right before it, let me add that.

2023-10-12 07:50 UTC, sergio-carlavilla commented
Can you please share your email to me? carlavilla@FreeBSD.org
Use the email please, GitHub will remove it if you put it here

2023-10-14 09:28 UTC, grahamperrin requested changes

2023-10-14 09:28 UTC, grahamperrin commented on documentation/content/en/books/handbook/disks/_index.adoc
> +* Supports multiple cryptographic algorithms such as AES-XTS,  AES-CBC, and Camellia-CBCAES.
```suggestion
* Supports multiple cryptographic algorithms such as AES-XTS, AES-CBC, and Camellia-CBCAES.
```

2024-02-24 13:32 UTC, dbaio commented
Hello.

Thanks for your contribution.

To properly register your contribution, we will need your e-mail and name. This is what we are receiving [at this moment](https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-doc/pull/258.patch):

```
Garrett Boone <47018474+garrettboone@users.noreply.github.com>
```

Alternatively, if you prefer not to share your email, that's perfectly fine. We can simply add a line like this in the commit message:

```
Submitted by:    your name or username
```

Just let us know what you prefer.

Regards.

2024-02-24 14:00 UTC, garrettboone commented
@dbaio Hi, I just emailed to you the address to use. Sorry for the inconvenience - and thank you!

2024-02-24 18:02 UTC, dbaio commented
Committed on 38044feb6ef81364a7fe0294ae08cd2b6b44301b
Thank you!

2024-02-24 18:02 UTC, closed without merging