2023q3: dpaa2: Status update
freebsd/freebsd-doc pull request #259
Opened 2023-09-23 12:12 UTC by dsalychev

2023-09-23 19:30 UTC, grahamperrin requested changes

2023-09-23 19:30 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +Queues and Buffers Manager (QBMan, Rx/Tx queues control, Rx buffer pools) and the others. The Management Complex runs NXP-supplied firmware which provides DPAA2 objects as an abstraction layer over t
```suggestion
DPAA2 is a hardware-level networking architecture found in some NXP SoCs which contain hardware blocks including Management Complex (MC, a command interface to manipulate DPAA2 objects), Wire Rate I/O processor (WRIOP, packets distribution, queuing, drop decisions), Queues and Buffers Manager (QBMan, Rx/Tx queues control, Rx buffer pools) and others.
The Management Complex runs NXP-supplied firmware which provides DPAA2 objects as an abstraction layer over those blocks to simplify access to the underlying hardware.
```

2023-09-23 19:30 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +* link:https://github.com/mcusim/freebsd-src/issues?q=is%3Aissue+is%3Aclosed[List of all closed issues].
```suggestion
* Isolation between DPAA2 channels is link:https://cgit.freebsd.org/src/commit/?id=58983e4b0253ad38a3e1ef2166fedd3133fdb552[improved].
* Panic under heavy network load is link:https://github.com/mcusim/freebsd-src/issues/19[fixed].
* FDT/ACPI MDIO support.
* NFS root mount link:https://github.com/mcusim/freebsd-src/issues/7[no longer hangs] on netboot over DPAA2.
* Drivers link:https://github.com/mcusim/freebsd-src/issues/2[started] to communicate with MC via their own command portals (DPMCP).
* link:https://github.com/mcusim/freebsd-src/issues?q=is%3Aissue+is%3Aclosed[List of all closed issues].
```

2023-09-23 19:30 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +* Work on link:https://cgit.freebsd.org/src/commit/?id=2a9021898c4ee2154787da862c238cfeccd655df[dev/sff] started to support SFF/SFP modules in order to test DPAA2 drivers on the links above 1 Gbit/s
```suggestion
Work on link:https://cgit.freebsd.org/src/commit/?id=2a9021898c4ee2154787da862c238cfeccd655df[dev/sff] started to support SFF/SFP modules in order to test DPAA2 drivers on links above 1 Gbit/s.
```

2023-09-23 19:30 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +* Further parts (DPSW, DCE, etc.) supported by the hardware.
```suggestion
* Heavy network load tests (2.5 Gbit/s, 10 Gbit/s) and bottlenecks mitigation.
* Cached memory-backed software portals.
* Driver resources de-allocation to unload `dpaa2.ko` properly.
* Further parts (DPSW, DCE, etc.) supported by the hardware.
```

2023-09-23 19:35 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +Queues and Buffers Manager (QBMan, Rx/Tx queues control, Rx buffer pools) and the others. The Management Complex runs NXP-supplied firmware which provides DPAA2 objects as an abstraction layer over t
> … blocks including … Management Complex …, Queues and Buffers Manager (…) and others.

That's _including_, not _comprising_, so you can lose the two words at the tail of the sentence: 

> … blocks including … Management Complex …, and Queues and Buffers Manager (…).

2023-09-24 10:58 UTC, dsalychev commented
Uhh, I've force-pushed changes... sorry. @grahamperrin Could you take a look?

2023-09-24 13:14 UTC, grahamperrin requested changes

2023-09-24 13:14 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +link:https://github.com/mcusim/freebsd-src[DPAA2 on Github]
```suggestion
Links: +
link:https://cgit.freebsd.org/src/tree/sys/dev/dpaa2[DPAA2 in the FreeBSD source tree] URL: link:https://cgit.freebsd.org/src/tree/sys/dev/dpaa2[] +
link:https://github.com/mcusim/freebsd-src[DPAA2 on Github] URL: link:https://cgit.freebsd.org/src/tree/sys/dev/dpaa2[]
```

Whilst the repetitions, prefixes etc. do appear peculiar, some peculiarities are currently required for the eventual plain text edition of the report to include visible or usable links. See, for example, last quarter's:

* https://lists.freebsd.org/archives/freebsd-announce/2023-July/000077.html

2023-09-24 13:14 UTC, grahamperrin commented
> Uhh, I've force-pushed changes... sorry. 

IMHO (drive-by reviewer, not a status team member): no harm done, but thanks.

2023-09-27 12:16 UTC, lsalvadore requested changes
A few changes and it is ready.

2023-09-27 12:16 UTC, lsalvadore commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +Sponsor: Bare Enthusiasm :) +
I am sure that this is one of the most important sponsors, but I discourage listing it: I guess it holds for almost any project, it does not give any new real information, and there is also the risk that the importance of the real economical sponsor is underestimated.

2023-09-28 09:38 UTC, lsalvadore approved these changes
I have found one last small thing that you can fix at commit time.
Approved, thanks.

2023-09-28 09:38 UTC, lsalvadore commented on website/content/en/status/report-2023-07-2023-09/dpaa2.adoc
> +URL: link:https://github.com/mcusim/freebsd-src[]
```suggestion
link:https://cgit.freebsd.org/src/tree/sys/dev/dpaa2[DPAA2 in the FreeBSD source tree] URL: link:https://cgit.freebsd.org/src/tree/sys/dev/dpaa2[] +
link:https://github.com/mcusim/freebsd-src[DPAA2 on Github] URL: link:https://github.com/mcusim/freebsd-src[]
```

2023-10-01 12:54 UTC, grahamperrin commented
https://github.com/freebsd/freebsd-doc/pull/259#issuecomment-1732544892

> Uhh, I've force-pushed changes... sorry. 

<https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273895> intended to clarify the situation, and is closed as fixed, however I don't see the fix. 

@dsalychev sorry.

2023-10-02 08:45 UTC, lsalvadore commented
Merged in commit 7a4522d6295fddc50799a4e93864d0c8baf22f6e, thanks.

2023-10-02 08:45 UTC, closed without merging