2023q3 report for the openstack on freebsd project
freebsd/freebsd-doc pull request #272
Opened 2023-09-29 08:57 UTC by starbops

2023-09-29 09:28 UTC, lwhsu commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +Looking ahead to Q4, our focus is wrapping up the POC with revised documentation and porting to FreeBSD 14.0-CURRENT.
I think we can say 14.0-RELEASE.

2023-09-29 11:36 UTC, starbops commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +Looking ahead to Q4, our focus is wrapping up the POC with revised documentation and porting to FreeBSD 14.0-CURRENT.
Updated, thanks!

2023-10-01 20:29 UTC, grahamperrin requested changes

2023-10-01 20:29 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +We also addressed the nest bhyve issue in our development environment mentioned in the last quarterly report.
```suggestion
We also addressed the nest bhyve issue in our development environment mentioned in https://www.freebsd.org/status/report-2023-04-2023-06/#_openstack_on_freebsd[the last quarterly report].
```

Side note: the word _nest_ was not mentioned.

2023-10-01 20:29 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +We also aim to rebase our work with the OpenStack link:https://releases.openstack.org/antelope/index.html[2023.1 Antelope].
```suggestion
We also aim to rebase our work with OpenStack link:https://releases.openstack.org/antelope/index.html[2023.1 Antelope].
```

2023-10-01 20:29 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +This is also important because right now we don't have a port for the managed DHCP service in Neutron.
```suggestion
This is also important because right now we do not have a port for the managed DHCP service in Neutron.
```

2023-10-01 20:29 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +Throughout this quarter, we've focused on the last bit of the entire POC, the VM console integration.
```suggestion
Throughout this quarter, we focused on the last bit of the entire proof of concept (POC), the VM console integration.
```

Avoid contractions (a style guideline).

2023-10-01 20:29 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +It's worth mentioning that in the development of the hook script, we found that the hook interface provided by Libvirt specifically for bhyve was link:https://gitlab.com/libvirt/libvirt/-/issues/528[
```suggestion
During development of the hook script, we found that the hook interface provided by Libvirt specifically for bhyve was link:https://gitlab.com/libvirt/libvirt/-/issues/528[not well implemented].
```

Avoid contractions and (another guideline) be concise.

2023-10-02 07:54 UTC, lsalvadore requested changes
Approved once the small nits are fixed.

2023-10-02 07:54 UTC, lsalvadore commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +However, bhyve does not natively expose serial consoles, so we need to instead export the man:nmdm[4] device over the network.
```suggestion
However, man:bhyve[8] does not natively expose serial consoles, so we need to instead export the man:nmdm[4] device over the network.
```

2023-10-02 13:12 UTC, starbops commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +We also addressed the nest bhyve issue in our development environment mentioned in the last quarterly report.
The wording is slightly different. I've updated the sentence with context. Thank you.

2023-10-02 13:13 UTC, starbops commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +However, bhyve does not natively expose serial consoles, so we need to instead export the man:nmdm[4] device over the network.
Updated, thanks!

2023-10-04 21:00 UTC, lsalvadore approved these changes
I have found one last small thing to fix, but I can do it when I merge the report.

Approved, thanks.

2023-10-05 04:10 UTC, starbops commented on website/content/en/status/report-2023-07-2023-09/openstack-on-freebsd.adoc
> +Our host's CPUs have these two features so we need to disable them at the L1 guest, which acts as a bhyve host, in `/boot/loader.conf` to make L2 guests not hanging.
Thanks for the notice!

2023-10-05 09:10 UTC, lsalvadore commented
Merged, thanks.

2023-10-05 09:10 UTC, closed without merging