Pot/Potluck Report
freebsd/freebsd-doc pull request #273
Opened 2023-09-29 15:46 UTC by hny-gd

2023-09-29 16:04 UTC, grembo commented on website/content/en/status/report-2023-07-2023-09/pot.adoc
> +Additionally, a new release for the link:https://github.com/bsdpot/nomad-pot-driver[Nomad Pot Driver] that allows setting Pot attributes in Nomad job descriptions will very likely be available by the
@hny-gd v0.9.1 was released today, portstree update will happen tomorrow latest.

2023-09-29 16:04 UTC, grembo commented on website/content/en/status/report-2023-07-2023-09/pot.adoc
> +Last not least, link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273583[a patch] for the link:https://www.freshports.org/devel/sccache/[sccache port] was submitted to include sccache-dist and i
@hny-gd This also landed today.

2023-10-01 20:11 UTC, grahamperrin requested changes

2023-10-02 07:45 UTC, lsalvadore requested changes

2023-10-02 07:45 UTC, lsalvadore commented on website/content/en/status/report-2023-07-2023-09/pot.adoc
> +During this quarter, link:https://github.com/bsdpot/pot/pull/274[Pot 0.15.6] was finished, adding custom pf rule configuration hooks.
```suggestion
During this quarter, link:https://github.com/bsdpot/pot/pull/274[Pot 0.15.6] was finished, adding custom man:pf[4] rule configuration hooks.
```

2023-10-02 07:45 UTC, lsalvadore commented on website/content/en/status/report-2023-07-2023-09/pot.adoc
> +Last not least, link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273583[a patch] adding build cluster support to the link:https://www.freshports.org/devel/sccache/[sccache port] was committed.
I think the commit is in `ports` not in `src`, hence
```suggestion
Last but not least, a patch (gitref:90b1184d93c8[repository=ports]) added build cluster support to the package:devel/sccache[] port.
```

2023-10-02 13:53 UTC, hny-gd commented
@grahamperrin and @lsalvadore thank you very much for your edits, I committed them.

2023-10-02 14:35 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/pot.adoc
> +Last not least, link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273583[a patch] adding build cluster support to the link:https://www.freshports.org/devel/sccache/[sccache port] was committed.
@lsalvadore thanks, sorry for my error (copy-and-paste from Bugzilla, an oversight with edition).

2023-10-04 21:10 UTC, lsalvadore approved these changes
Approved, thanks.

2023-10-05 09:12 UTC, lsalvadore commented
Merged, thanks.

2023-10-05 09:12 UTC, closed without merging