Status: 2023Q3: SquashFS report
freebsd/freebsd-doc pull request #274
Opened 2023-09-29 17:21 UTC by Mashijams

2023-10-01 19:52 UTC, grahamperrin requested changes

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +link:https://github.com/Mashijams/freebsd-src/tree/gsoc/testing[Source code] URL: https://github.com/Mashijams/freebsd-src/tree/gsoc/testing[]
```suggestion
Links: +
link:https://wiki.freebsd.org/SummerOfCode2023Projects/PortSquashFuseToTheFreeBSDKernel[Wiki page] URL: link:https://wiki.freebsd.org/SummerOfCode2023Projects/PortSquashFuseToTheFreeBSDKernel[] +
link:https://github.com/Mashijams/freebsd-src/tree/gsoc/testing[Source code] URL: link:https://github.com/Mashijams/freebsd-src/tree/gsoc/testing[]
```

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +read-only filesystem operations.
```suggestion
This quarter we finished SquashFS driver work for the kernel.
We now can mount SquashFS archives on FreeBSD 13.2-RELEASE or greater, and perform all basic read-only filesystem operations.
```

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +We also implemented extended attributes interface functions for SquashFS and all the work remaining for them is to implement their kernel interface hooks.
```suggestion
We also implemented extended attributes interface functions for SquashFS.
All that remains is to implement their kernel interface hooks.
```

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +which kernel for some reason skips while listing dirents.
```suggestion
There were a lot of bug fixes as well.
One major issue was to find out why we can not list the first entry of the root directory, it transpires that SquashFS could have `inode_number` as zero, which the kernel, for some reason, skips while listing dirents.
```

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +For now, we fixed it by passing dummy inode_number to dirent instead of zero.
```suggestion
For now, we fixed it by passing dummy `inode_number`, instead of zero, to dirent.
```

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +I'm happy to say that SquashFS will find its place in upcoming FreeBSD releases.
```suggestion
I am happy to say that SquashFS will find its place in upcoming FreeBSD releases.
```

2023-10-01 19:52 UTC, grahamperrin commented on website/content/en/status/report-2023-07-2023-09/squashfs.adoc
> +I'm happy to say that SquashFS will find its place in upcoming FreeBSD releases.
This formality is according to [a guideline for the FreeBSD Documentation Project](https://docs.freebsd.org/en/books/fdp-primer/book/#writing-style-guidelines).

2023-10-02 07:40 UTC, lsalvadore commented
Thanks @Mashijams for you report and thanks @grahamperrin for your review. I will approve and merge this report once the things noted by Graham will be fixed.

2023-10-04 21:12 UTC, lsalvadore approved these changes
Approved, thanks.

2023-10-05 09:12 UTC, lsalvadore commented
Merged, thanks.

2023-10-05 09:12 UTC, closed without merging