Small correction about architectures near the beginning of the page
freebsd/freebsd-doc pull request #281
Opened 2023-10-14 11:31 UTC by duckyondiscord

2023-10-16 00:14 UTC, bsdjhb commented
A good clarification, but I might reword it a bit further as:

```
The `amd64` indicates that the system in this example is running the port of FreeBSD to the 64-bit x86 architecture.
```

2023-10-17 17:59 UTC, igalic requested changes
note that while  ducky is a perfectly fine name, we don't accept contributions from emails that we can't actually email to, especially <x@users.noreply.github.com>

2023-10-21 13:34 UTC, duckyondiscord commented
> note that while ducky is a perfectly fine name, we don't accept contributions from emails that we can't actually email to, especially [x@users.noreply.github.com](mailto:x@users.noreply.github.com)
Alright well you can email me at duccywastaken@pm.me then, I should add it to my github profile.

2023-10-21 13:37 UTC, duckyondiscord commented
> A good clarification, but I might reword it a bit further as:
> 
> ```
> The `amd64` indicates that the system in this example is running the port of FreeBSD to the 64-bit x86 architecture.
> ```

I personally think that's unnecessarily complicating it a little. You can make that change if you want but I think simpler's better in this case.

2023-10-22 03:31 UTC, grahamperrin requested changes

2023-10-22 03:31 UTC, grahamperrin commented on documentation/content/en/books/handbook/basics/_index.adoc
> +The `amd64` indicates that the system in this example is running an x86 64-bit version of FreeBSD.
```suggestion
`amd64` indicates x86, 64-bit.
```
The [existing context](https://docs.freebsd.org/en/books/handbook/basics/#consoles):

<details>
<summary>screen shot</summary>

![image](https://github.com/freebsd/freebsd-doc/assets/192271/59189c3a-6572-4523-919f-0f98ad34b07a)

</details>

* a FreeBSD site
* a FreeBSD document.
* the _FreeBSD/_ part of `FreeBSD/amd64` needs no explanation. 

https://people.freebsd.org/~grahamperrin/style/writing/tips/ | be concise :-)

2023-10-22 09:56 UTC, grahamperrin commented
https://github.com/freebsd/freebsd-doc/pull/281#issuecomment-1763549288

>> … the port of FreeBSD to …

+1

I get it, however …

… if I close my eyes, intentionally not reminding myself of what's already at page, I imagine <https://www.freebsd.org/about/> being a good/better place for something along the lines of: 

> FreeBSD and much of the complementary software in its ports collection is ported to ….

(Clumsily worded, but you get the idea.)

If a newcomer dives straight into the 'FreeBSD Basics' chapter with no prior knowledge of FreeBSD, no prior knowledge of the concept of porting: the reader might look away to <https://docs.freebsd.org/en/books/handbook/glossary/#_p> or <https://www.freebsd.org/ports/>  for a meaning of the word _port_.

HTH, happy to discuss in Matrix or IRC (to not derail things here).

2023-10-24 14:51 UTC, duckyondiscord commented
Is there anything else I need to do here?

2023-12-08 00:10 UTC, bsdjhb commented
Merged in 45ee577b18db51a4f64c3e64db1d3b409fc1d975.  Thanks!

2023-12-08 00:10 UTC, closed without merging