arch-handbook/boot: add a space between the next word and the previous stop
freebsd/freebsd-doc pull request #320
Opened 2024-01-03 04:52 UTC by rilysh

Currently, it's
> This range is used as a (fake) partition table for writing the MBR back to disk.Finally, the sector field 

It should be
> This range is used as a (fake) partition table for writing the MBR back to disk. Finally, the sector field

(Add a space)

2024-01-03 12:29 UTC, igalic requested changes
We usually do one sentence per line for easier diffs. looks like that's what's actually missing here

2024-01-06 07:23 UTC, rilysh commented
> We usually do one sentence per line for easier diffs. looks like that's what's actually missing here

Does it mean a commit message needs to be added before the email address?
e.g.
```
Hello world

Signed-off-by: mail
```

Sorry, I don't understand it. I'm not sure how FreeBSD does this, but an example of it would be nice!

2024-01-06 12:01 UTC, igalic commented
the format for the commit message can be found here https://github.com/freebsd/freebsd-doc/blob/main/.hooks/prepare-commit-msg#L44

what i was talking about is the format for the documentation: https://docs.freebsd.org/en/books/fdp-primer/writing-style/

2024-01-06 12:29 UTC, rilysh commented
> what i was talking about is the format for the documentation: https://docs.freebsd.org/en/books/fdp-primer/writing-style/

Perhaps but the first line is quite a bit small already, maybe if you or someone from doc team approves it, I will separate it too with in this PR.

https://docs.freebsd.org/en/books/fdp-primer/writing-style/#one-sentence-per-line
(I hope I understand the context).

2024-01-07 21:28 UTC, igalic commented
it doesn't matter how big or small the line is.
the main reason for doing this is to make the raw document readable in a text editor, and to make diffs readable.

diffs usually happen on sentence level, unless someone goes around and does done big restructuring.
so having one sentence per line really helps.

i don't know why this isn't the case here, but it should be.

this is an okay fix for the issue at hand.
a better fix would be to insert a newline instead of the space.

and an even better fix than that would be to do that for the entire document.

I hope this helps and provides you with guidance

2024-01-14 09:24 UTC, rilysh commented
@igalic  Thank you for your reply! It seems the documentation also adds new lines after a comma, but I'm not too sure about it. I saw a few examples, and sometimes there's a new line (after a comma) and sometimes there isn't.

I've updated the page (I didn't test it). I hope I didn't break anything, please let me know if anything is wrong.

2024-01-14 09:33 UTC, rilysh commented
Hmm, it's weird. On my editor it tab looks okay whereas on GitHub it looks different.
https://github.com/freebsd/freebsd-doc/pull/320/commits/9eb158ad49b5c1ecfffb5ea4acec6e144c4d7428#diff-b809eeca053495a1bb88831285c7b0326cb7b6065e7b510898d04e0f0eb8bb03R272

2024-01-14 10:34 UTC, igalic requested changes
hope this helps

2024-01-14 10:34 UTC, igalic commented on documentation/content/en/books/arch-handbook/boot/_index.adoc
> +and other low-level initialization so the CPU can set up the computer properly.
this is not a sentence

2024-01-14 10:34 UTC, igalic commented on documentation/content/en/books/arch-handbook/boot/_index.adoc
> +with no additional information (no ELF file format, for example).
this is not a sentence

2024-01-14 10:34 UTC, igalic commented on documentation/content/en/books/arch-handbook/boot/_index.adoc
> +as it defines some of the run-time behavior of [.filename]#boot0#.
this is not a sentence

2024-01-14 10:34 UTC, igalic commented on documentation/content/en/books/arch-handbook/boot/_index.adoc
> +and to build the output file "as is" (strip out any file formatting):
this is not a sentence

2024-01-14 10:34 UTC, igalic commented on documentation/content/en/books/arch-handbook/boot/_index.adoc
> +the number of times dictated by the `%cx` register.
this is not a sentence

2024-01-14 10:34 UTC, igalic commented on documentation/content/en/books/arch-handbook/boot/_index.adoc
> +The `movsw` instruction copies the word pointed to by `%si` to the address pointed to by `%di`.
this is

2024-01-14 10:48 UTC, rilysh commented
Thanks for your review! I've updated it.

2024-01-18 01:27 UTC, dbaio commented
@rilysh, thanks for your contribution.
@igalic, thanks for reviewing.

2024-01-18 01:27 UTC, closed without merging