handbook: fix cpufreq man link.
freebsd/freebsd-doc pull request #330
Opened 2024-01-16 21:57 UTC by vchimishuk

`man:` prefix is missing for `cpufreq`.

2024-01-16 22:00 UTC, igalic requested changes
please remove the . from the end of the commit message

otherwise, this pr looks good

2024-01-16 22:02 UTC, vchimishuk commented
> please remove the . from the end of the commit message
> 
> otherwise, this pr looks good

Amended. Force-pushed.

2024-01-16 22:07 UTC, igalic approved these changes
👍

2024-01-18 00:03 UTC, dbaio commented
Thank you for your contribution. I have only removed the .po change; there is no need to update .po files, as they are generated automatically.

2024-01-18 00:04 UTC, closed without merging