Status/2023Q4: Sort reports
freebsd/freebsd-doc pull request #335
Opened 2024-02-02 10:02 UTC by lsalvadore

Some reports are still missing and we are waiting for them. I will soon write an introduction.

2024-02-05 02:55 UTC, pauamma requested changes

2024-02-05 02:55 UTC, pauamma commented on website/content/en/status/report-2023-10-2023-12/_index.adoc
> +
clusteradm.adoc is missing.

2024-02-05 02:55 UTC, pauamma commented on website/content/en/status/report-2023-10-2023-12/_index.adoc
> +include::{reports-path}/doceng.adoc[]
Not consistent with the actual filename, doceng-2023-4th-quarter-status-report.adoc.

2024-02-10 22:31 UTC, pauamma approved these changes

2024-02-15 16:53 UTC, lsalvadore commented
Thanks!

2024-02-15 16:53 UTC, closed without merging