Add FreshPorts report
freebsd/freebsd-doc pull request #345
Opened 2024-03-01 13:39 UTC by dlangille

2024-03-01 15:13 UTC, pauamma approved these changes
Approved once these typos are fixed. (Fixable on commit.)

2024-03-01 15:13 UTC, pauamma commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +link:https://freshports..org[FreshPorts] URL: link:freshports.org[] +
Extra dot before "org".

2024-03-01 15:13 UTC, pauamma commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +can create a list of ports and receive notifcations about those ports. This
s/notifcations/notifications/

2024-03-01 15:13 UTC, pauamma commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +new feature can also notify when a new pacakge is available for that port.
s/pacakge/package/

2024-03-01 15:24 UTC, dlangille commented
Good changes, thanks.

2024-03-02 08:37 UTC, grahamperrin requested changes

2024-03-02 08:37 UTC, grahamperrin commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +link:https://freshports..org[FreshPorts] URL: link:freshports.org[] +
```suggestion
link:https://freshports.org/[FreshPorts] URL: link:https://freshports.org/[] +
```

- URL: link:https: (the weird norm)
- plus the correction from @pauamma

2024-03-02 08:37 UTC, grahamperrin commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +new feature can also notify when a new pacakge is available for that port.
```suggestion
One of the original features of FreshPorts is notification of ports updates.
You can create a list of ports and receive notifications about those ports.
This new feature can also notify when a new package is available for that port.
```

- one sentence per line
- plus the corrections from @pauamma

2024-03-02 08:37 UTC, grahamperrin commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +mailing list and let us know what you'd like to help with.
```suggestion
To contribute, please join the link:https://lists.freshports.org/mailman/listinfo/freshports-coders[] mailing list and let us know what you'd like to help with.
```

2024-03-02 08:37 UTC, grahamperrin commented on website/content/en/status/report-2024-01-2024-03/freshports.adoc
> +you the port has been patched, and then you wait for the package.
```suggestion
The use case: a known security vuln has been patched.
FreshPorts will tell you the port has been patched, and then you wait for the package.
```

2024-03-02 13:34 UTC, dlangille commented
Have I done all the things to bring in all the things?

2024-03-08 00:57 UTC, grahamperrin commented
> Have I done all the things to bring in all the things?

I guess so, thanks, however it's not for me to approve. 

----

Note to self: the _suggested changes_ feature brings simplicity, however in a case such as this – where I use the feature to suggest changes that originated from someone else – the commits do not show the other person's name. Sorry @pauamma

2024-03-08 17:02 UTC, lsalvadore approved these changes
Just two small more changes and this is ready for commit. Feel free to commit it yourself or I can commit it for you if you prefer.

Thanks for your report.

2024-03-08 17:18 UTC, dlangille commented
I hope I've covered all pending changes.

2024-03-20 08:55 UTC, closed without merging

2024-03-20 08:55 UTC, lsalvadore commented
Merged, thanks.