Status/2024Q1/bsdinstall.adoc: Add report
freebsd/freebsd-doc pull request #368
Opened 2024-04-08 22:41 UTC by khorben

Reflecting the current status of the integration, for a possible bootable image with a graphical installer to be generated from the base system.

Sponsored by:	The FreeBSD Foundation

2024-04-08 22:57 UTC, pauamma approved these changes
Other than that, LGTM.

2024-04-08 22:57 UTC, pauamma commented on website/content/en/status/report-2024-01-2024-03/bsdinstall.adoc
> +(In fact a link:https://github.com/khorben/freebsd-src/tree/khorben/bsdinstall-graphical5[khorben/bsdinstall-graphical5] branch already exists)
Needs "." before ")".

2024-04-11 21:43 UTC, pauamma approved these changes

2024-04-12 13:34 UTC, lsalvadore requested changes
Only two minor fixes and it is ready. If you prefer I can make the changes myself at merge time.

Thanks!

2024-04-13 10:29 UTC, lsalvadore commented
Merged, thanks!

2024-04-13 10:29 UTC, closed without merging