Guide users towards installing Plasma 6 / KDE 6 packages in handbook
freebsd/freebsd-doc pull request #423
Opened 2024-10-06 14:02 UTC by claucambra

Hello,

Now that Plasma 6 and related components are out it would seem the handbook should guide users towards installing the relevant `x11/kde6` packages and friends

Apologies if there are mistakes in these changes, I'm happy to address them

2024-10-10 02:39 UTC, pauamma requested changes
Only change the English original, not the translations. Only translation teams (and sometimes doceng@) deal with the latter.

Other than that, your change looks good to me (but then I don't use KDE).

2024-10-10 02:41 UTC, claucambra commented
> Only change the English original, not the translations. Only translation teams (and sometimes doceng@) deal with the latter.
> 
> Other than that, your change looks good to me (but then I don't use KDE).

Thanks for your review. I removed the modifications to the non-English handbook adocs

2024-10-10 02:51 UTC, pauamma approved these changes

2024-12-12 07:35 UTC, grahamperrin commented
With respect: this guidance may be premature. KDE 6 is still _devel_, and so on. 

<details>
<summary>Preparing to install x11/kde6 in a mounted, but not yet temporarily active, '1500029-008-kde6' boot environment with FreeBSD 15.0-CURRENT</summary>

```text
root@mowa219-gjp4-zbook-freebsd:~ # bectl list -c creation | tail -n 6
1500029-002-base        -      -          1.21G 2024-12-08 00:43
1500029-003-base        -      -          1.28G 2024-12-09 03:19
1500029-004-base        -      -          1.29G 2024-12-09 16:27
1500029-005-base        -      -          1.27G 2024-12-10 10:10
1500029-006-base        R      -          237G  2024-12-11 12:22
1500029-007-base-ports  N      /          3.06G 2024-12-12 04:51
root@mowa219-gjp4-zbook-freebsd:~ # bectl activate 1500029-007-base-ports
Successfully activated boot environment 1500029-007-base-ports
root@mowa219-gjp4-zbook-freebsd:~ # uname -bmvKU
FreeBSD 15.0-CURRENT main-n274158-e7bc16422031 GENERIC-NODEBUG amd64 1500029 1500029 95c9441ddc3fa3cfe1a54cd6369e44dee9013aab
root@mowa219-gjp4-zbook-freebsd:~ # tail -n 6 /home/grahamperrin/Documents/boot\ environments.txt
1500029-002-base                2024-12-08 00:43 main-n274083-53adc0b898a4 GENERIC-NODEBUG 6484e9ffa934f7b99fa5fba5e58645d881ddf22a
1500029-003-base                2024-12-09 03:19 main-n274101-30e8252353d9 GENERIC-NODEBUG c07ce745e24ffd5e7d8b71c50694ea4e4f272f40
1500029-004-base                2024-12-09 16:27 main-n274109-908f215e80fa GENERIC-NODEBUG 64e45c839930f9a5b127806f705a1c3c8559a742
1500029-005-base                2024-12-10 10:10 main-n274127-3ca117c6bb1d GENERIC-NODEBUG 99abd83199f182a4934b789af693460f80b1af4e
1500029-006-base                2024-12-11 12:22 main-n274154-36a80f426435 GENERIC-NODEBUG ad8f2717a4c88b2f7e933725efcd2913134c11d2
1500029-007-base-ports          2024-12-12 04:51 main-n274158-e7bc16422031 GENERIC-NODEBUG 95c9441ddc3fa3cfe1a54cd6369e44dee9013aab
root@mowa219-gjp4-zbook-freebsd:~ # pkg update -r FreeBSD-base && pkg update -r FreeBSD-ports ; date
Updating FreeBSD-base repository catalogue...
FreeBSD-base repository is up to date.
All repositories are up to date.
Updating FreeBSD-ports repository catalogue...
FreeBSD-ports repository is up to date.
All repositories are up to date.
Thu Dec 12 07:20:20 GMT 2024
root@mowa219-gjp4-zbook-freebsd:~ # bectl create 1500029-008-kde6
root@mowa219-gjp4-zbook-freebsd:~ # bectl mount 1500029-008-kde6 /tmp/up
/tmp/up
root@mowa219-gjp4-zbook-freebsd:~ # pkg search kde6
The provides database is up-to-date.
kde6-devel-6.2.3.24.01.90      KDE Plasma Desktop and Applications (current)
root@mowa219-gjp4-zbook-freebsd:~ # pkg rquery %o kde6-devel
The provides database is up-to-date.
x11/kde6
root@mowa219-gjp4-zbook-freebsd:~ # time pkg -r /tmp/up install --yes --quiet --fetch-only --repository FreeBSD-ports x11/kde6
Conflicts with the existing packages have been found.
One more solver iteration is needed to resolve them.
25.223u 3.856s 1:42.80 28.2%    3203+548k 1210+2613io 1912pf+0w
root@mowa219-gjp4-zbook-freebsd:~ # time pkg -r /tmp/up install --yes --fetch-only --repository FreeBSD-ports x11/kde6
…
```

</details>

`  - konsole-devel-24.01.90 [FreeBSD-ports] conflicts with konsole-23.08.5_1 [installed] on /usr/local/bin/konsole`

I'd like to (at least) tell whether we have, in the main tree, the fix for a significant bug that affected Konsole. 

Thanks

2024-12-13 00:44 UTC, grahamperrin commented
FreeBSD reports: 

- [283295 – x11/konsole-devel: illegible characters in title bars and tabs (KDE bug 480196)](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=283295)
- [283296 – x11-fm/dolphin-devel: crashes when opened (unusable)](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=283296)

In my brief test this morning, I did not have time to tell whether fixes for these four KDE bugs have reached the main tree of the FreeBSD ports collection: 

- [479950 – Dolphin Information Panel not available](https://bugs.kde.org/show_bug.cgi?id=479950)
- [480864 – Titlebar context menu of non-maximized Aurorae-decorated windows is misplaced on Wayland](https://bugs.kde.org/show_bug.cgi?id=480864)
- [481952 – On X11, panels are hidden after minimizing Dolphin window](https://bugs.kde.org/show_bug.cgi?id=481952)
- [482689 – Title bar context menu shows up at a wrong position](https://bugs.kde.org/show_bug.cgi?id=482689) – X11, not Wayland – IIRC in my previous test (not this morning) this was still broken in our main tree.

2025-03-09 00:43 UTC, grahamperrin requested changes
Timing: packages for 5 will disappear from ports quarterly after the 2025Q2 branch is created. We'll see this branch at pages such as <https://cgit.freebsd.org/ports/>.

2025-03-09 00:43 UTC, grahamperrin commented on documentation/content/en/books/handbook/desktop/_index.adoc
> +| x11/kde6
```suggestion
| x11/kde
```

2025-03-12 12:25 UTC, claucambra commented on documentation/content/en/books/handbook/desktop/_index.adoc
> +| x11/kde6
Thanks for the suggestion, I've now addressed it

2025-07-27 11:21 UTC, sergio-carlavilla commented
Fixed in: https://cgit.freebsd.org/doc/commit/?id=ed5a326bec9da9785835f9a22b39e75c2058f181

Sorry for the big delay

2025-07-27 11:21 UTC, closed without merging