handbook: Adjust wording of statement in updating/upgrading
freebsd/freebsd-doc pull request #441
Opened 2024-12-07 12:26 UTC by jrac

The introductory line of 26.8, "Building on non-FreeBSD Hosts" states:

"Nowadays, the FreeBSD can be build on Linux distributions and macOS."

"can be build on" should be "can be built on".

", the FreeBSD can' should be ", FreeBSD can".

2024-12-12 06:53 UTC, grahamperrin requested changes

2024-12-12 06:53 UTC, grahamperrin commented on documentation/content/en/books/handbook/cutting-edge/_index.adoc
>  Historically, building FreeBSD required a FreeBSD host.
```suggestion
Historically, building required a FreeBSD host.
```

2024-12-12 06:53 UTC, grahamperrin commented on documentation/content/en/books/handbook/cutting-edge/_index.adoc
> +Nowadays, FreeBSD can be built on Linux distributions and macOS.
```suggestion
Nowadays, FreeBSD can be built on Linux and macOS.
```

Technical neat to say _Linux distributions_, however yer average reader will understand what's meant by _Linux_.

2024-12-12 06:53 UTC, grahamperrin commented on documentation/content/en/books/handbook/cutting-edge/_index.adoc
>  To build FreeBSD on non-FreeBSD hosts, the recommendation is to use the `tools/build/make.py` script.
```suggestion
To build on a non-FreeBSD host, the `tools/build/make.py` script is recommended.
```

2024-12-12 06:55 UTC, grahamperrin commented
Nice catch, Josh. Suggested changes are for conciseness. Thanks.

2024-12-22 12:47 UTC, pauamma approved these changes

2024-12-28 21:56 UTC, dbaio commented
Committed on https://github.com/freebsd/freebsd-doc/commit/adc3f7a7fb298265652a2780e46dbf0f09c93469
Thank you all!

2024-12-28 21:56 UTC, closed without merging