Info for serving poudriere packages privately
freebsd/freebsd-doc pull request #66
Opened 2022-04-15 19:19 UTC by fearedbliss

This adds a small section to the "Configuring pkg Clients to Use a Poudriere Repository" showing the user how to point to their packages repository (package directory in this case) via `file://`. Allowing the user to not have to publicly expose their packages over the internet.

2022-04-17 03:34 UTC, pauamma commented
LGTM

2022-04-20 08:51 UTC, debdrup commented
In order to credit you properly with `git commit --author "Jonathan Vasquez <jon@xyinn.org>"`?

2022-04-20 12:14 UTC, fearedbliss commented
@debdrup Thank you. That's correct :).

2022-04-20 13:30 UTC, debdrup requested changes
Alright, I've had a little time to review it now, and I've found a couple of things.

Firstly, [we have some writing style guidelines](https://docs.freebsd.org/en/books/fdp-primer/book/#writing-style) that I think need to be applied to this.

Secondly, I think it needs to be broken into multiple sentences and have the parenthesis moved - it's a bit too run-on as it is, and the parenthesis feels more like a conditional clause that could be worded better.

Overall, I think it's a good change though - so if you can run over the FDP (not just the section I linked to), adjust as necessary, and keep in mind the other thing, I think we can get this landed in short order. :)

2022-04-20 17:51 UTC, fearedbliss commented
@debdrup Thanks for the feedback :). I'll take a look at the guidelines and push another change.

2022-04-24 17:56 UTC, fearedbliss commented
@debdrup I finally got a chance to take a look at the FreeBSD guidelines and philosophy for writing. After looking at it, I've realized that my personal philosophy for technical writing is very different (and I highly prefer writing informally since I like to feel (and want the reader to feel) closer). There's many other things as well but that's one of the main ones. For this reason I've decided to close this PR. If someone really wants to include this change then I encourage them to take what I wrote and convert it to the FreeBSD style appropriately.

Thanks for taking the time to take a look at my PR and give me feedback. I felt it was necessary to at least give a reason as to why I would continue rather than just silently close it.

Take care!

2022-04-24 17:56 UTC, closed without merging

2022-05-13 18:10 UTC, fearedbliss commented
@debdrup Hey, since recently I got a chance to spend a lot more time in the docs (mostly reading), I re-read most of the FDP again and decided to take another crack at this. I checked out a copy of the docs locally and decided to open the following PR:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263955

We can continue further discussion on there since this branch is stale anyways and I generated a diff for submission via the problem report interface instead.

I'll be using this experience as an opportunity to further improve my "formal technical writing" as oppose to my "informal technical writing" :D.