Update ZFS arc min/max sysctl loader variables
freebsd/freebsd-doc pull request #92
Opened 2022-10-31 04:40 UTC by xor-gate

Update arc min and max loader syctl variable names based on 13.1-RELEASE-p2

2022-10-31 08:50 UTC, pauamma requested changes

2022-10-31 08:50 UTC, pauamma commented on documentation/content/en/books/handbook/zfs/_index.adoc
> +* [[zfs-advanced-tuning-arc_max]] `_vfs.zfs.arc.max_` (legacy `_vfs.zfs.arc_max`) - Upper size of the <<zfs-term-arc,ARC>>. The default is all RAM but 1 GB, or 5/8 of all RAM, whichever is more. Use
I'd be explicit about versions and use:
> `_vfs.zfs.arc.max_` starting with 13.x (`_vfs.zfs.arc_max` for 12.x)

2022-10-31 08:50 UTC, pauamma commented on documentation/content/en/books/handbook/zfs/_index.adoc
> +* [[zfs-advanced-tuning-arc_min]] `_vfs.zfs.arc.min_` (legacy `_vfs.zfs.arc_min`) - Lower size of the <<zfs-term-arc,ARC>>. The default is one half of `vfs.zfs.arc_meta_limit`. Adjust this value to p
Same here.

2022-10-31 20:59 UTC, xor-gate commented
Good comments @pauamma fixed in https://github.com/freebsd/freebsd-doc/pull/92/commits/99cc596880c90404afea83ee75ffb52e8899926f. I did not dig deep to get to know which when was introduced and deprecated. Thanks!

2022-10-31 23:32 UTC, pauamma reviewed
Text LGTM now. Will try building as soon as I remember how to get a raw diff from GitHub.

2022-11-01 01:56 UTC, pauamma commented
Almost there. vfs.zfs.arc_meta_limit became vfs.zfs.arc.meta_limit in 13.x as well. (Didn't notice on first round.)

How do you want to credited for this patch? (Name and email address.)

2022-11-01 18:29 UTC, xor-gate commented
Did a vim search on leftovers but found some more inconsistencies. You can credit me on Jerry Jacobs<jerry.jacobs[_at_]xor-gate.org>. Thanks for pointing out the meta_limit. I did not a scan of legacy on the whole sysctl range.

2022-11-01 18:29 UTC, xor-gate commented
Review comments again fixed in https://github.com/freebsd/freebsd-doc/pull/92/commits/6d509de41e5082f056d00fff8efcf1f36f16a461

2022-11-02 03:17 UTC, pauamma commented
Assumption check: do you want your email address recorded as-is with the obfuscation?

2022-11-02 03:31 UTC, pauamma approved these changes

2022-11-02 04:56 UTC, xor-gate commented
> Assumption check: do you want your email address recorded as-is with the obfuscation?

Remove the obfuscation, replace with `@` :-). Email harvest bots can be nasty 👍 . Thanks for having me fixing this issues in the docs, it was nice working together to fix this @pauamma

2022-11-02 22:08 UTC, closed without merging

2022-11-02 22:18 UTC, pauamma commented
> Thanks for having me fixing this issues in the docs, it was nice working together to fix this @pauamma

Thank you for submitting it! Committed.